version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            pip install coverage
            pip install nose
            nosetests --with-coverage --cover-package=girth --cover-html testing/
          name: Test
      - store_artifacts:
          path: htmlcov          

workflows:
  main:
    jobs:
      - build-and-test
