version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            pip install --user coverage
            pip install --user nose
            nosetests --with-coverage --cover-package=girth testing/
            bash <(curl -s https://codecov.io/bash)
          no_output_timeout: 2m

          name: Test

workflows:
  main:
    jobs:
      - build-and-test
